CREATE TABLE "films" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "description" varchar(200),
  "release_date" date NOT NULL,
  "duration" int NOT NULL,
  "rating_id" int
);

CREATE TABLE "mpa_ratings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(10)
);

CREATE TABLE "genres" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20)
);

CREATE TABLE "films_genres" (
  "film_id" int,
  "genre_id" int,
  PRIMARY KEY ("film_id", "genre_id")
);

CREATE TABLE "films_users_who_liked" (
  "film_id" int,
  "user_id" int,
  PRIMARY KEY ("film_id", "user_id")
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "login" varchar(50) NOT NULL,
  "email" varchar(50) NOT NULL,
  "birthday" date NOT NULL
);

CREATE TABLE "friendship" (
  "user1_id" int,
  "user2_id" int,
  "status_id" int,
  PRIMARY KEY ("user1_id", "user2_id")
);

CREATE TABLE "friendship_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20)
);

COMMENT ON COLUMN "films"."name" IS 'not blank';

COMMENT ON COLUMN "films"."release_date" IS 'after 28 Dec 1985';

COMMENT ON COLUMN "films"."duration" IS 'positive, in seconds';

COMMENT ON COLUMN "users"."login" IS 'without spaces';

COMMENT ON COLUMN "users"."email" IS 'not blank, contains @';

COMMENT ON COLUMN "users"."birthday" IS 'in past or present';

ALTER TABLE "films" ADD FOREIGN KEY ("rating_id") REFERENCES "mpa_ratings" ("id");

ALTER TABLE "films_genres" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");

ALTER TABLE "films_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");

ALTER TABLE "films_users_who_liked" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");

ALTER TABLE "films_users_who_liked" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "friendship" ADD FOREIGN KEY ("user1_id") REFERENCES "users" ("id");

ALTER TABLE "friendship" ADD FOREIGN KEY ("user2_id") REFERENCES "users" ("id");

ALTER TABLE "friendship" ADD FOREIGN KEY ("status_id") REFERENCES "friendship_status" ("id");
