spring:
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always

logging:
  level:
    org.zalando.logbook: TRACE